---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 3-demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: 3-demo
  url: https://github.com/devopsravi9/bb-app-source.git
