---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-demo-hr
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./nginx-ingress-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: helm-demo-git
  interval: 1m0s
  targetNamespace: default
  values:
    replicaCount: 2
